### ISSUE TITLE
Flow Lines Point to Wrong Artboard

### ISSUE THREAD

**Issue by sfriedlander** [abynim/UserFlows.sketchplugin#42] opened 2017-01-18 17:06 UTC
When I try to create a link from a symbol to a new artboard, the arrow is pointing to the wrong artboard, not the one I selected.  I have already made many links in this document but now it stopped working correctly. Can an artboard go corrupt to cause this?

**Comment by richardquay** [comment] 2017-01-19 20:36
Running into the same issue. 

From what I can tell, if I duplicate the artboard then it seem to always link back to the original artboard.

**Comment by scrumit** [comment] 2017-01-20 11:39
isn't this a duplicate of issue #40?

**Comment by abynim** [comment] 2017-01-21 03:14
Thanks @scrumit. This is in fact a duplicate of issue #40 and is fixed in v2.0.4. Thanks for reporting @sfriedlander and @richardquay.

**Closed as completed** 2017-01-21 03:14 UTC
