### ISSUE TITLE
can not create userflow diagram

### ISSUE THREAD

**Issue by dew90730** [abynim/UserFlows.sketchplugin#161] opened 2019-02-08 02:01 UTC
v.2.3.3, latest version
can not create userflow diagram.
it just creates a copied artboard and an copied image of the artboard selected as 'start from'.

sketch is version 53, which is the latest one.

**Comment by abynim** [comment] 2019-02-08 04:25
@dew90730 Please add a screenshot of your UserFlows settings so I can reproduce your exact environment. Thanks!

**Comment by meekjt** [comment] 2019-02-20 21:24
@abynim I have the same issue, here are my settings:
<img width="486" alt="screen shot 2019-02-20 at 16 23 13" src="https://user-images.githubusercontent.com/6875502/53125364-d7173900-352b-11e9-8cbf-8ac35bc94453.png">

**Comment by janusc** [comment] 2019-02-24 21:25
Have the same problem. 
![image](https://user-images.githubusercontent.com/129480/53305511-a7956300-3882-11e9-90de-506965ba5406.png)

Screenshot of where the plugin doesn't create a new page and there is a bitmap of the first selected artboard on top of the artboard.

Really appreciate your plugin a lot :-)

**Comment by abynim** [comment] 2019-02-26 04:07
@meekjt @janusc Thanks for reporting. Do you see errors logged in Console.app when trying to generate a diagram?

**Comment by danielthall** [comment] 2019-03-03 05:10
I am having the same issue with Sketch 53.2

Here is the output to the console:

```
TypeError: instance.detachByReplacingWithGroup is not a function. (In 'instance.detachByReplacingWithGroup()', 'instance.detachByReplacingWithGroup' is undefined)
line: 769
sourceURL: /Users/danielthall/Library/Application Support/com.bohemiancoding.sketch3/Plugins/UserFlows.sketchplugin/Contents/Sketch/script.js
column: 49
stack: recursivelyDetachSymbolInstance@/Users/danielthall/Library/Application Support/com.bohemiancoding.sketch3/Plugins/UserFlows.sketchplugin/Contents/Sketch/script.js:769:49
artboardWithDetachedSymbolsFromArtboard@/Users/danielthall/Library/Application Support/com.bohemiancoding.sketch3/Plugins/UserFlows.sketchplugin/Contents/Sketch/script.js:791:34
generateFlowWithSettings@/Users/danielthall/Library/Application Support/com.bohemiancoding.sketch3/Plugins/UserFlows.sketchplugin/Contents/Sketch/script.js:1100:63
generateFlow@/Users/danielthall/Library/Application Support/com.bohemiancoding.sketch3/Plugins/UserFlows.sketchplugin/Contents/Sketch/script.js:924:27
```

**Comment by abynim** [comment] 2019-03-03 09:35
Thanks @danielthall the log was very helpful. Could you please install the version from this branch and confirm if the issue is fixed: https://github.com/abynim/UserFlows/tree/sketch53-2-compatibility

**Comment by danielthall** [comment] 2019-03-03 09:37
@abynim You're amazing! Yes, that fixed it. Thank you so much.

**Comment by abynim** [comment] 2019-03-03 10:12
Awesome! Thanks for confirming. Merged 👍

**Comment by danielthall** [comment] 2019-03-05 04:08
@abynim Sorry- but I am seeing another error on another machine. Same file, same sketch version, using the latest plugin release:

```
TypeError: null is not an object (evaluating 'sketch.fromNative(instance).detach().sketchObject')
line: 771
sourceURL: /Users/hmi/Library/Application Support/com.bohemiancoding.sketch3/Plugins/UserFlows.sketchplugin/Contents/Sketch/script.js
column: 50
stack: recursivelyDetachSymbolInstance@/Users/hmi/Library/Application Support/com.bohemiancoding.sketch3/Plugins/UserFlows.sketchplugin/Contents/Sketch/script.js:771:50
recursivelyDetachSymbolInstance@/Users/hmi/Library/Application Support/com.bohemiancoding.sketch3/Plugins/UserFlows.sketchplugin/Contents/Sketch/script.js:783:35
recursivelyDetachSymbolInstance@/Users/hmi/Library/Application Support/com.bohemiancoding.sketch3/Plugins/UserFlows.sketchplugin/Contents/Sketch/script.js:783:35
recursivelyDetachSymbolInstance@/Users/hmi/Library/Application Support/com.bohemiancoding.sketch3/Plugins/UserFlows.sketchplugin/Contents/Sketch/script.js:783:35
recursivelyDetachSymbolInstance@/Users/hmi/Library/Application Support/com.bohemiancoding.sketch3/Plugins/UserFlows
```

**Comment by abynim** [comment] 2019-03-05 07:59
@danielthall does it also show the same error message? In your previous log you had `TypeError: ...` but that's missing here.

**Comment by danielthall** [comment] 2019-03-05 08:08
I'm sorry, I had a formatting error with my comment! I just updated it.

**Comment by danielthall** [comment] 2019-03-06 13:31
I can confirm that this doesn't always occur. Some flows seem to be fine, while others have a TypeError almost immediately. Trying to dig in and see if I can tell what it is that it doesn't like.

**Comment by abynim** [comment] 2019-03-06 23:27
Yeah, I could not reproduce this at all. Will dig deeper this weekend when I have some more time. At the very least I can wrap it in a `try.. catch` and have it fail elegantly whenever it does. 
Thanks for helping debug this @danielthall 🙌

**Comment by danielthall** [comment] 2019-03-07 00:29
@abynim Good thinking! I just did that locally and it seems to have fixed it.


Looking into it, I think I have identified the actual problem. I have a symbol that is called `Transparent` that I use as a color override sometimes. That is actually just a blank symbol with nothing in it, and that's what was causing the error. I don't think I actually need this symbol anymore, but even so, failing gracefully doesn't negatively impact the production of the generated flow diagram.

**Comment by danielthall** [comment] 2019-03-11 14:14
@abynim Would you like me to create a PR for adding the `try ... catch`?

**Comment by danielthall** [comment] 2019-05-03 17:08
@abynim Following up about this issue. Happy to put a PR in

**Comment by abynim** [comment] 2019-05-04 00:10
@danielthall Yes please, that would be very much appreciated. Thanks for following up 🙏

**Comment by danielthall** [comment] 2019-05-09 16:48
@abynim I have the work done in a branch, but I don't have access to make a PR here

**Comment by abynim** [comment] 2019-05-12 03:28
Added you as a collaborator 👍 Please feel free to merge your changes unless you think a review is absolutely required.

**Comment by danielthall** [comment] 2019-05-12 05:57
Cool thanks! Just merged into the v2 branch!

**Closed as completed** 2019-05-12 05:57 UTC
