### ISSUE TITLE
Generate User Flows crashes Sketch 50.2

### ISSUE THREAD

**Issue by Alesclandre** [abynim/UserFlows.sketchplugin#131] opened 2018-07-04 09:01 UTC
Hello, everytime I try to generate a userflow, it crashes Sketch... 
I tried another version of your plugin (v2.0.6) but no popup are shown (nothing happens).
Here is what my console says for the crashing version (v2.1.3) : 
```
04/07/2018 10:57:07,362 Generate Flow Diagram (Sketch)[2359]: TypeError: null is not an object (evaluating 'screenLayer.absoluteRect')
line: 808
sourceURL: /me/Library/Application Support/com.bohemiancoding.sketch3/Plugins/UserFlows.sketchplugin/Contents/Sketch/script.js
column: 14
```

**Comment by abynim** [comment] 2018-07-06 02:04
@Alesclandre does it crash with a specific document or does it also crash with new documents? For Sketch 50+ you should be using the latest version of UserFlows (2.1.3), older versions will not work.

**Comment by Alesclandre** [comment] 2018-07-06 08:03
@abynim Here is what i've just did : 

1. I've just opened Sketch 50.2 and created a new document, 
2. created 2 artboards
3. created one rectangle on the first artboard
4. Selected the rectangle and the second artboard
5. Created link
6. Generate the flow diagram
7. And then crashes...

I can send you a crash report if you wish

**Comment by abynim** [comment] 2018-07-06 09:00
Could you please post a screenshot of your UserFlows Settings? I cannot reproduce the crash. Maybe Im missing some setting.

**Comment by Alesclandre** [comment] 2018-07-06 14:45
Here they are (in French) . I'm on Mac OS 10.11.6. 
I also removed my name
![capture d ecran 2018-07-06 a 16 44 21](https://user-images.githubusercontent.com/34575194/42385148-37e8888c-813c-11e8-849f-b326d2f0afbb.png)

**Comment by Alesclandre** [comment] 2018-07-06 14:49
But hey you know what ? With the default user settings, it works !
It might be the strength of the stroke

**Comment by Alesclandre** [comment] 2018-07-06 14:53
And now that it worked once, I can't make it crash...

**Comment by abynim** [comment] 2018-07-08 03:37
Glad it's working. Let's close this issue for now, but please reopen it and let me know if you encounter another crash 👍

**Closed as completed by abynim** 2018-07-08 03:37 UTC
