### ISSUE TITLE
Plugin doesn't work as expected in Sketch Version 67.1 (100412)

### ISSUE THREAD

**Issue by acarlenaon** [abynim/UserFlows.sketchplugin#173] opened 2020-07-06 16:32 UTC
Hi there Aby!

First of all, thanks for such a useful plugin, it's really a life saver for me & the other designers of the team. I wanted to reach out to you to report a weird behaviour when I generate the user flow in the last version of sketch: after all the connections are made, when I try to Generate User Flow (Add to page _Flows & the two checkboxes enabled) the folder with the connections goes invisible, the flow isn't generated in a new page (_Flows) and the bitmaps generated appear on top of the artboards.

could you look up into this? thank you in advance!

Alejandro

**Comment by abynim** [comment] 2020-07-07 02:00
Hi Alejandro, I can't seem to reproduce this issue. Could you please post a screenshot of your UserFlows > Settings? It could be some setting that's breaking it so it'll be easier to debug if I can recreate your environment here.

Also, if possible, can you please check Console.app (available in Applications > Utilities) and see if there are any error logs when you run the Generate User Flow command? You can filter logs by typing "Sketch" in the search field.

Thanks for reporting the issue. I'm happy to know your team and you find the plugin useful!

**Comment by enniz** [comment] 2020-07-07 14:59
Hi Aby, thanks for your great work done on User Flow it is a very lifesaver plugin and the only user flow tool which actually works.

I'm experiencing the same issue as Alejandro using the version: 67.2 (100443). I'm able to draw the flow but it's impossible to generate it.

I've recorded my screen so that you can have a better view of what is happening. 
you can view it at the following link:
[https://www.dropbox.com/s/5dcbedf16qydqim/userflow_issue.mov?dl=0](url)

The console logs an Object-C exception. `Error: An Obj-C exception occurred.
    at [native code] (/)
    at generateFlowWithSettings (/Users/Enniz/Library/Application Support/com.bohemiancoding.sketch3/Plugins/UserFlows.sketchplugin/Contents/Sketch/script.js:1058:111)
    at generateFlow (/Users/Enniz/Library/Application Support/com.bohemiancoding.sketch3/Plugins/UserFlows.sketchplugin/Contents/Sketch/script.js:926:27)
  nativeException: [<MSAbsoluteLayerRect 0x600019260b70> valueForUndefinedKey:]: this class is not key value coding-compliant for the key rulerY.`

I really hope you can fix it, thanks in advance.
Marco.

**Comment by abynim** [comment] 2020-07-08 01:27
Hi Marco, thanks for the video and the error log. That made it quite easy to find the issue. I've published a fix in a separate branch. Could you please install the plugin from here and let me know if the issue is resolved so I can merge it into the main branch? Get it here: https://github.com/abynim/UserFlows/archive/sketch-67-fixes.zip

**Comment by enniz** [comment] 2020-07-08 06:36
Hi Aby, the fix works 🥳  🥳  🥳. Thanks so much!!!!

**Comment by abynim** [comment] 2020-07-08 07:04
Thanks for the confirmation. Changes have been merged.

**Closed as completed by abynim** 2020-07-08 07:04 UTC

**Comment by acarlenaon** [comment] 2020-07-08 15:31
Thank you both sorry for not being able to respond earlier!
