### ISSUE TITLE
New link connected to one artboard

### ISSUE THREAD

**Issue by work-leonid** [abynim/UserFlows.sketchplugin#41] opened 2017-01-17 10:26 UTC
Hi! After updating User flows 2.0.3 (from 2.0.0) links don't work http://take.ms/i5m4K
Sketch 41.2 (35397), MacOS Sierra 10.12 (16A323), User Flows 2.0.3

**Comment by abynim** [comment] 2017-01-18 02:26
This happens when the artboard you're linking to is a duplicate of another artboard. The bug was introduced in the latest update and Im working on a fix. Let's keep track of the bug in issue #40

**Closed as completed by abynim** 2017-01-18 02:26 UTC
Labels: duplicate
